version: '2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
     - default
    hostname: mongodb
    volumes:
    - mongo:/data/db:rw
  app:
    image: console-master-demo
    depends_on:
    - mongo
volumes:
  mongo:
    driver: local