version: '2'
services:
  app:
    image: console-app-demo

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local