version: '2'
networks:
  default:
    ipam:
      driver: default
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '8001:8001'
      - '6379:6379'
    networks:
     - default
    hostname: cache
        
    volumes: 
      - cache:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s 
  app:
    image: console-app-demo
    depends_on:
    - cache
  
volumes:
  cache:
    driver: local