version: '2'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
     - my-net
    hostname: cache
        
    volumes: 
      - cache:/data
  app:
    image: console-app-demo
    depends_on:
    - cache

volumes:
  cache:
    driver: local

networks:
  my-net:
